on:
  pull_request:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.workflow_sha }}"
      - run: echo "wf-hash-${{ hashFiles('.github/workflows/pr.yml') }}"
      - run: echo "Third Step"
